api_version = "2024-01"
type = "theme"
name = "Cart Progress Bar"
handle = "cart-progress-bar"

[[theme_extension.blocks]]
type = "cart-progress"
name = "Cart Progress Bar"
target = "section"

[[theme_extension.blocks]]
type = "announcement-progress"
name = "Announcement Progress Bar"
target = "section"
